name = "navsphere"
compatibility_date = "2024-11-11"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[env.production.vars]
GITHUB_ID = "Ov23lidDlTU4nHighwMx"
GITHUB_OWNER = "zhaozi1"
GITHUB_REPO = "NavSphere"
GITHUB_BRANCH = "main"
NEXTAUTH_URL = "https://navsphere-o3l.pages.dev/"
NEXT_PUBLIC_API_URL="https://navsphere-o3l.pages.dev/"

